---
title: "About"
author: "Aleks Galstyan"
format: html
toc: true
toc-title: "Table of Contents"
number-sections: true
---

# Introduction

On this site, an analysis of the **Billboard** charts was conducted using historical data.  
The results of the study are presented through clear and informative **graphs**, highlighting trends and changes over time.


# Results

The graphs below illustrate key findings of the analysis.  
They help trace the evolution of musical preferences, as well as the popularity of different genres and artists over time.

# Conclusion

This analysis provided valuable insights into the development of the music industry and listener preferences, based on Billboard chart data.

# Sources

The main source was the **Billboard charts** database, which was publicly available, and *ChatGpt* was also used to create charts and analyze the database.

**Dataset**: [https://www.kaggle.com/datasets/dhruvildave/billboard-the-hot-100-songs](billboard-the-hot-100-songs)


---